# Generated by Django 5.0.3 on 2024-04-01 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temple_name', models.CharField(max_length=20)),
                ('famous_for', models.CharField(max_length=20)),
                ('temple_address', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('devotees_per_day', models.IntegerField()),
                ('donation_mode', models.CharField(choices=[('Online', 'ONLINE'), ('Cash', 'Cash')], max_length=10)),
            ],
        ),
    ]
